/**
 * Export helpers for chat answers: clipboard copy, Databricks notebook
 * download (engineer mode), and Jira wiki-markup conversion (PM mode).
 */

const FENCE_RE = /```(\w*)\n([\s\S]*?)```/g

/** Copy text to the clipboard. Falls back to execCommand for non-HTTPS
 *  internal deployments where navigator.clipboard is unavailable. */
export async function copyText(text) {
  try {
    if (navigator.clipboard?.writeText) {
      await navigator.clipboard.writeText(text)
      return true
    }
  } catch {}
  try {
    const ta = document.createElement('textarea')
    ta.value = text
    ta.style.position = 'fixed'
    ta.style.opacity = '0'
    document.body.appendChild(ta)
    ta.select()
    const ok = document.execCommand('copy')
    document.body.removeChild(ta)
    return ok
  } catch {
    return false
  }
}

/** Extract fenced code blocks from markdown: [{ lang, code }] */
export function extractCodeBlocks(markdown) {
  const blocks = []
  for (const m of (markdown ?? '').matchAll(FENCE_RE)) {
    blocks.push({ lang: (m[1] || '').toLowerCase(), code: m[2].trimEnd() })
  }
  return blocks
}

/**
 * Build a Databricks "source" notebook (.py) from an engineer answer's
 * SQL / Python code blocks. Importing the file into a Databricks workspace
 * recreates the cells. Returns null when the answer has no runnable blocks.
 */
export function buildDatabricksNotebook(markdown) {
  const blocks = extractCodeBlocks(markdown).filter(
    b => b.lang === 'sql' || b.lang === 'python' || b.lang === 'py'
  )
  if (!blocks.length) return null

  const cells = blocks.map(b => {
    if (b.lang === 'sql') {
      const magic = b.code.split('\n').map(line => `# MAGIC ${line}`).join('\n')
      return `# MAGIC %sql\n${magic}`
    }
    return b.code
  })

  return [
    '# Databricks notebook source',
    '# MAGIC %md',
    '# MAGIC ### Validation notebook — generated by Rule Intelligence',
    '',
    '# COMMAND ----------',
    '',
    cells.join('\n\n# COMMAND ----------\n\n'),
    '',
  ].join('\n')
}

/** Trigger a client-side file download. */
export function downloadFile(filename, content, mime = 'text/plain') {
  const blob = new Blob([content], { type: `${mime};charset=utf-8` })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

/**
 * Convert a markdown user story to Jira wiki markup so it pastes cleanly
 * into Jira description fields (headings, bullets, bold, code).
 */
export function markdownToJira(markdown) {
  // Protect fenced code blocks from the line-level conversions below.
  const codeBlocks = []
  let text = (markdown ?? '').replace(FENCE_RE, (_, lang, code) => {
    const token = `@@JIRACODE${codeBlocks.length}@@`
    const tag = lang ? `{code:${lang}}` : '{code}'
    codeBlocks.push(`${tag}\n${code.trimEnd()}\n{code}`)
    return token
  })

  text = text
    .split('\n')
    .map(line => {
      const heading = line.match(/^(#{1,6})\s+(.*)$/)
      if (heading) return `h${heading[1].length}. ${heading[2]}`
      const bullet = line.match(/^(\s*)-\s+(.*)$/)
      if (bullet) return `${bullet[1]}* ${bullet[2]}`
      const numbered = line.match(/^(\s*)\d+\.\s+(.*)$/)
      if (numbered) return `${numbered[1]}# ${numbered[2]}`
      return line
    })
    .join('\n')

  text = text
    .replace(/\*\*([^*]+)\*\*/g, '*$1*')               // bold
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '[$1|$2]')    // links
    .replace(/`([^`]+)`/g, '{{$1}}')                   // inline code

  return text.replace(/@@JIRACODE(\d+)@@/g, (_, i) => codeBlocks[Number(i)])
}
